# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: "Check code and build"
    cmds:
      - task: check
      - go build

  check:
    desc: "Check code"
    cmds:
      - task: format
      - task: vet
      - go mod tidy

  format:
    desc: "Format code"
    cmds:
      - go fmt ./...

  vet:
    desc: "Vet code"
    cmds:
      - go vet ./...

  test:
    desc: "Build and run tests"
    deps:
      - build
    cmds:
      - go test -v ./...

  goreleaser:
    deps:
      - build
    desc: "Build with GoReleaser and show built version"
    cmds:
      - goreleaser check
      # @see https://goreleaser.com/cmd/goreleaser_build/
      - goreleaser build --single-target --snapshot --clean
      - ./dist/*/gh-itkdev --version

  coding-standards-check:
    desc: "Apply and check coding standards"
    cmds:
      - task: coding-standards-apply
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '**/*.md'

  coding-standards-apply:
    desc: "Apply coding standards"
    cmds:
      - docker run --rm --volume $PWD:/md peterdavehello/markdownlint markdownlint --ignore LICENSE.md '**/*.md' --fix
