# https://taskfile.dev

version: "3"

vars:
  APP_NAME: gh-itkdev

tasks:
  default:
    cmds:
      - task --list
    silent: true

  build:
    desc: "Check code and build"
    sources:
      - "**/*.go"
    generates:
      - "{{.APP_NAME}}"
    cmds:
      - go get -u ./...
      - go mod tidy
      - task: format
      - task: check
      - go build

  format:
    desc: "Format code"
    cmds:
      - go fmt ./...
      - task format:gofumpt
      - task format:golangci-lint

  format:gofumpt:
    desc: Run gofumpt if installed (https://github.com/mvdan/gofumpt)
    cmds:
      - |
        if command -v gofumpt >/dev/null 2>&1; then
          gofumpt -l -w .
        fi

  format:golangci-lint:
    desc: Run golangci-lint if installed (https://golangci-lint.run)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint fmt
        fi

  check:
    desc: "Check code"
    cmds:
      - go vet ./...
      - task: check:gofumpt
      - task: check:golangci-lint

  check:gofumpt:
    desc: Run gofumpt if installed (https://github.com/mvdan/gofumpt)
    cmds:
      - |
        if command -v gofumpt >/dev/null 2>&1; then
          gofumpt -l .
        fi

  check:golangci-lint:
    desc: Run golangci-lint if installed (https://golangci-lint.run)
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run
        fi

  test:
    desc: "Build and run tests"
    deps:
      - build
    cmds:
      - go test -v ./...

  goreleaser:
    deps:
      - build
    desc: "Build with GoReleaser and show built version"
    cmds:
      - goreleaser check
      # @see https://goreleaser.com/cmd/goreleaser_build/
      - goreleaser build --single-target --snapshot --clean
      - ./dist/*/{{.APP_NAME}} --version

  coding-standards:markdown:apply:
    desc: "Apply Markdown coding standards"
    cmds:
      - docker compose run --rm markdownlint markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: "Apply and check Markdown coding standards"
    cmds:
      - task: coding-standards:markdown:apply
      - docker compose run --rm markdownlint markdownlint '**/*.md'

  coding-standards:yaml:apply:
    desc: "Apply YAML coding standards"
    cmds:
      - docker compose run --rm prettier '**/*.{yml,yaml}' --write

  coding-standards:yaml:check:
    desc: "Apply and check YAML coding standards"
    cmds:
      - task: coding-standards:yaml:apply
      - docker compose run --rm prettier '**/*.{yml,yaml}' --check

  coding-standards:apply:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:markdown:apply
      - task: coding-standards:yaml:apply

  coding-standards:check:
    desc: "Apply and check coding standards"
    cmds:
      - task: coding-standards:markdown:check
      - task: coding-standards:yaml:check
