name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v1
        with:
          # @TODO https://github.com/cli/gh-extension-precompile/issues/50#issuecomment-1980217293
          go_version: 1.22
